from tkinter import Toplevel, Label, Entry, Button


def changerNumeroTelView(menu):
    change_tel = Toplevel(menu)
    change_tel.title("Changer numéro téléphone")
    change_tel.geometry("480x320")
    text_font = ("Boulder", 20, 'bold')
    premier_numero = Label(change_tel, text=0, font=text_font)
    premier_numero.place(relx=0, rely=0.3)
    deuxieme_numero = Label(change_tel, text=0, font=text_font)
    deuxieme_numero.place(relx=0.1, rely=0.3)
    troisieme_numero = Label(change_tel, text=0, font=text_font)
    troisieme_numero.place(relx=0.2, rely=0.3)
    quatrieme_numero = Label(change_tel, text=0, font=text_font)
    quatrieme_numero.place(relx=0.3, rely=0.3)
    cinquieme_numero=Label(change_tel, text=0, font=text_font)
    cinquieme_numero.place(relx=0.4, rely=0.3)
    sixieme_numero=Label(change_tel, text=0, font=text_font)
    sixieme_numero.place(relx=0.5, rely=0.3)
    septieme_numero=Label(change_tel, text=0, font=text_font)
    septieme_numero.place(relx=0.6, rely=0.3)
    huitieme_numero=Label(change_tel, text=0, font=text_font)
    huitieme_numero.place(relx=0.7, rely=0.3)
    neuvieme_numero=Label(change_tel, text=0, font=text_font)
    neuvieme_numero.place(relx=0.8, rely=0.3)
    dizieme_numero=Label(change_tel, text=0, font=text_font)
    dizieme_numero.place(relx=0.9, rely=0.3)
