from hardware.multiple_servos import enclencher_servo_remplissage_haut,enclencher_servo_remplissage_bas
import time
enclencher_servo_remplissage_haut(0)
enclencher_servo_remplissage_haut(1)
time.sleep(1)
enclencher_servo_remplissage_bas(0)
enclencher_servo_remplissage_bas(1)
time.sleep(1)
enclencher_servo_remplissage_haut(0)
enclencher_servo_remplissage_haut(1)